export type Film = {
  id: number;
  title: string;
  tagline: string;
  synopsis: string;
  posterUrl: string;
  backdropUrl: string;
  releaseYear: number;
  genres: string[];
  cast: { name: string; character: string; avatarUrl: string }[];
  reviews: { author: string; text: string; rating: number }[];
  durationMinutes: number;
};

export const films: Film[] = [
  {
    id: 1,
    title: 'Echoes of the Void',
    tagline: 'Silence is the loudest scream.',
    synopsis: 'A lone astronaut on a deep space mission discovers a mysterious signal that forces her to confront her past and the nature of reality itself.',
    posterUrl: 'https://placehold.co/500x750',
    backdropUrl: 'https://placehold.co/1920x1080',
    releaseYear: 2024,
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    cast: [
      { name: 'Anya Sharma', character: 'Dr. Aris Thorne', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Ben Carter', character: 'Control (voice)', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [
      { author: 'IndieWire', text: 'A mind-bending journey into the unknown.', rating: 4.5 },
      { author: 'FilmThreat', text: 'Visually stunning and deeply philosophical.', rating: 5 },
    ],
    durationMinutes: 112,
  },
  {
    id: 2,
    title: 'The Last Bloom',
    tagline: 'Hope survives.',
    synopsis: 'In a post-apocalyptic world where plant life is extinct, a young girl finds the last surviving seed and must protect it from a desperate society.',
    posterUrl: 'https://placehold.co/500x751',
    backdropUrl: 'https://placehold.co/1920x1081',
    releaseYear: 2023,
    genres: ['Drama', 'Adventure'],
    cast: [
      { name: 'Lily Chen', character: 'Elara', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Marcus Boone', character: 'Kael', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'ScreenAnarchy', text: 'A touching story of resilience.', rating: 4 }],
    durationMinutes: 98,
  },
  {
    id: 3,
    title: 'Cobblestone Rhapsody',
    tagline: 'Every street has a story.',
    synopsis: 'An ensemble dramedy following the interconnected lives of several residents of a quirky, historic city block over the course of one transformative summer.',
    posterUrl: 'https://placehold.co/500x752',
    backdropUrl: 'https://placehold.co/1920x1082',
    releaseYear: 2022,
    genres: ['Comedy', 'Drama', 'Romance'],
    cast: [
      { name: 'Javier Morales', character: 'Mateo', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Chloe Dubois', character: 'Amelie', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Sam Jones', character: 'The Old Man', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Variety', text: 'Charming and witty, a true gem.', rating: 4.5 }],
    durationMinutes: 124,
  },
  {
    id: 4,
    title: 'Neonoir',
    tagline: 'The city never sleeps, but it has nightmares.',
    synopsis: 'A jaded private investigator in a rain-drenched, futuristic city takes on a case that leads him into a conspiracy involving cybernetic enhancements and corporate espionage.',
    posterUrl: 'https://placehold.co/500x753',
    backdropUrl: 'https://placehold.co/1920x1083',
    releaseYear: 2024,
    genres: ['Neo-Noir', 'Sci-Fi', 'Mystery'],
    cast: [
      { name: 'Kenji Tanaka', character: 'Jax', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Eva Rostova', character: 'Aura', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'The Hollywood Reporter', text: 'A stylish and gritty cyberpunk thriller.', rating: 4 }],
    durationMinutes: 130,
  },
  {
    id: 5,
    title: 'The Sunken Crown',
    tagline: 'Some treasures are best left unfound.',
    synopsis: 'A disgraced marine biologist obsessed with a mythical shipwreck must lead a perilous expedition to the ocean depths, only to find the legend is terrifyingly real.',
    posterUrl: 'https://placehold.co/500x754',
    backdropUrl: 'https://placehold.co/1920x1084',
    releaseYear: 2021,
    genres: ['Horror', 'Adventure'],
    cast: [
      { name: 'Isla Fisher', character: 'Dr. Maren', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'David Oyelowo', character: 'Captain Jax', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Dread Central', text: 'Claustrophobic and chilling.', rating: 4 }],
    durationMinutes: 105,
  },
  {
    id: 6,
    title: 'Paper & Glue',
    tagline: 'Some bonds can\'t be broken.',
    synopsis: 'A quiet, heartfelt story about an elderly bookbinder who forms an unlikely friendship with a troubled teenager through their shared love of restoring old books.',
    posterUrl: 'https://placehold.co/500x755',
    backdropUrl: 'https://placehold.co/1920x1085',
    releaseYear: 2023,
    genres: ['Drama'],
    cast: [
      { name: 'Sir Patrick Stewart', character: 'Arthur', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Jenna Ortega', character: 'Mia', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'RogerEbert.com', text: 'A beautifully crafted film about connection.', rating: 5 }],
    durationMinutes: 92,
  },
  {
    id: 7,
    title: 'The Whistleblower of Silicon Valley',
    tagline: 'The truth has a price.',
    synopsis: 'Based on a true story, this film follows the software engineer who exposed a massive data privacy scandal at a top tech company, risking her career and safety.',
    posterUrl: 'https://placehold.co/500x756',
    backdropUrl: 'https://placehold.co/1920x1086',
    releaseYear: 2022,
    genres: ['Thriller', 'Biography', 'Drama'],
    cast: [
      { name: 'Carey Mulligan', character: 'Hannah Sterling', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Riz Ahmed', character: 'Jamal Khan', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'The Guardian', text: 'A tense and important story for our time.', rating: 4.5 }],
    durationMinutes: 128,
  },
  {
    id: 8,
    title: 'Crimson Peak',
    tagline: 'Beware of Crimson Peak.',
    synopsis: 'In the aftermath of a family tragedy, an aspiring author is torn between love for her childhood friend and the temptation of a mysterious outsider. Trying to escape the ghosts of her past, she is swept away to a house that breathes, bleeds... and remembers.',
    posterUrl: 'https://placehold.co/500x757',
    backdropUrl: 'https://placehold.co/1920x1087',
    releaseYear: 2015,
    genres: ['Gothic', 'Romance', 'Horror'],
    cast: [
      { name: 'Mia Wasikowska', character: 'Edith Cushing', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Jessica Chastain', character: 'Lucille Sharpe', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Tom Hiddleston', character: 'Thomas Sharpe', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Empire', text: 'Gorgeously gothic and splendidly sinister.', rating: 4 }],
    durationMinutes: 119,
  },
  {
    id: 9,
    title: 'The Farewell',
    tagline: 'Based on an actual lie.',
    synopsis: 'A Chinese family discovers their grandmother has only a short while left to live and decides to keep her in the dark, scheduling a wedding to gather before she dies.',
    posterUrl: 'https://placehold.co/500x758',
    backdropUrl: 'https://placehold.co/1920x1088',
    releaseYear: 2019,
    genres: ['Comedy', 'Drama'],
    cast: [
      { name: 'Awkwafina', character: 'Billi Wang', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Tzi Ma', character: 'Haiyan Wang', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Zhao Shuzhen', character: 'Nai Nai', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'A.V. Club', text: 'A funny, moving, and deeply personal story.', rating: 5 }],
    durationMinutes: 100,
  },
  {
    id: 10,
    title: 'Hunt for the Wilderpeople',
    tagline: 'The comeback story of the year.',
    synopsis: 'A national manhunt is ordered for a rebellious kid and his foster uncle who go missing in the wild New Zealand bush.',
    posterUrl: 'https://placehold.co/500x759',
    backdropUrl: 'https://placehold.co/1920x1089',
    releaseYear: 2016,
    genres: ['Adventure', 'Comedy', 'Drama'],
    cast: [
      { name: 'Sam Neill', character: 'Hec', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Julian Dennison', character: 'Ricky', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'IGN', text: 'An absolutely delightful and hilarious adventure.', rating: 4.8 }],
    durationMinutes: 101,
  },
  {
    id: 11,
    title: 'Sound of Metal',
    tagline: 'The world is gone. The silence is all.',
    synopsis: 'A heavy-metal drummer\'s life is thrown into freefall when he begins to lose his hearing.',
    posterUrl: 'https://placehold.co/500x760',
    backdropUrl: 'https://placehold.co/1920x1090',
    releaseYear: 2019,
    genres: ['Drama', 'Music'],
    cast: [
      { name: 'Riz Ahmed', character: 'Ruben Stone', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Olivia Cooke', character: 'Lou Berger', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Rolling Stone', text: 'A powerful and immersive cinematic experience.', rating: 5 }],
    durationMinutes: 120,
  },
  {
    id: 12,
    title: 'First Cow',
    tagline: 'Some fortunes are built on a lie.',
    synopsis: 'A skilled cook has traveled west and joined a group of fur trappers in Oregon. He finds a true connection with a Chinese immigrant also seeking his fortune. Soon the two collaborate on a successful business.',
    posterUrl: 'https://placehold.co/500x761',
    backdropUrl: 'https://placehold.co/1920x1091',
    releaseYear: 2019,
    genres: ['Drama', 'Western'],
    cast: [
      { name: 'John Magaro', character: 'Cookie Figowitz', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Orion Lee', character: 'King-Lu', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'The New York Times', text: 'A quiet masterpiece of friendship and capitalism.', rating: 5 }],
    durationMinutes: 122,
  },
  {
    id: 13,
    title: 'The Florida Project',
    tagline: 'A story of a childhood summer.',
    synopsis: 'Set on a stretch of highway just outside the imagined utopia of Disney World, The Florida Project follows six-year-old Moonee and her rebellious mother Halley over the course of a single summer.',
    posterUrl: 'https://placehold.co/500x762',
    backdropUrl: 'https://placehold.co/1920x1092',
    releaseYear: 2017,
    genres: ['Drama'],
    cast: [
      { name: 'Brooklynn Prince', character: 'Moonee', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Willem Dafoe', character: 'Bobby Hicks', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Bria Vinaite', character: 'Halley', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Vulture', text: 'Vibrant, heartbreaking, and unforgettable.', rating: 5 }],
    durationMinutes: 111,
  },
  {
    id: 14,
    title: 'Leave No Trace',
    tagline: 'They can\'t live in our world. We can\'t live in theirs.',
    synopsis: 'A father and his thirteen-year-old daughter are living an ideal existence in a vast urban park in Portland, Oregon, when a small mistake derails their lives forever.',
    posterUrl: 'https://placehold.co/500x763',
    backdropUrl: 'https://placehold.co/1920x1093',
    releaseYear: 2018,
    genres: ['Drama'],
    cast: [
      { name: 'Ben Foster', character: 'Will', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Thomasin McKenzie', character: 'Tom', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Slate', text: 'A profoundly moving and compassionate film.', rating: 5 }],
    durationMinutes: 109,
  },
  {
    id: 15,
    title: 'Pig',
    tagline: 'We don\'t get a lot of things to really care about.',
    synopsis: 'A truffle hunter who lives alone in the Oregonian wilderness must return to his past in Portland in search of his beloved foraging pig after she is kidnapped.',
    posterUrl: 'https://placehold.co/500x764',
    backdropUrl: 'https://placehold.co/1920x1094',
    releaseYear: 2021,
    genres: ['Drama', 'Mystery', 'Thriller'],
    cast: [
      { name: 'Nicolas Cage', character: 'Rob Feld', avatarUrl: 'https://placehold.co/100x100' },
      { name: 'Alex Wolff', character: 'Amir', avatarUrl: 'https://placehold.co/100x100' },
    ],
    reviews: [{ author: 'Collider', text: 'A soulful meditation on grief and loss, with a stellar performance from Cage.', rating: 4.5 }],
    durationMinutes: 92,
  },
];
